pass destructor of StatusManager if sys is None
ClimateImpactLab/impactlab-tools pull request #466
Opened 2021-08-23 13:03 UTC by emileten

- [x ] closes #xxxx
 - [x] tests added / passed
 - [ ] docs reflect changes
 - [ ] passes ``flake8 impactlab_tools tests docs``
 - [ ] whatsnew entry

2021-08-23 13:05 UTC, emileten commented
@jrising this allows us to avoid the kind of problem described [here](https://gitlab.com/ClimateImpactLab/Impacts/impact-calculations/-/issues/195). It's basically simply turning off the very exception we're getting. I think it's better than a `try/except` since it's circumventing only the cases where `sys` is None. 

Did you have something like this in mind ? Thanks !

2021-08-23 15:53 UTC, jrising requested changes

2021-08-23 15:53 UTC, jrising commented on impactlab_tools/utils/paralog.py
> +        if sys is not None:
I think we should also check that this is a `DoubleLogger`. Otherwise, someone else may have replaced it and not want it to be overwritten.

2021-08-23 15:53 UTC, jrising commented on impactlab_tools/utils/paralog.py
> +        else:
Do we need this `else` clause?

2021-08-24 07:36 UTC, emileten commented on impactlab_tools/utils/paralog.py
> +        else:
we don't ! Thanks !

2021-08-24 16:05 UTC, emileten commented
@jrising I addressed your two comments !

2021-08-25 13:48 UTC, jrising approved these changes
Perfect, thanks! I'll merge it in.

2021-08-25 13:48 UTC, merged